const BORDER_RADIUS = 15;
const COLUMN_NUMBER_MOBILE = 2;
const COLUMN_NUMBER_TABLET = 3;
const COLUMN_NUMBER_DESKTOP = 4;
const GRID_GAP = 20;
const DEFAULT_ROW_HEIGHT = 0;

export {
  BORDER_RADIUS,
  COLUMN_NUMBER_MOBILE,
  COLUMN_NUMBER_DESKTOP,
  COLUMN_NUMBER_TABLET,
  GRID_GAP,
  DEFAULT_ROW_HEIGHT
};
